# Generated by Django 6.0.2 on 2026-02-24 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_qr_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qr_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
