@baseUrl = http://192.168.1.14:8000/api
@contentType = application/json

############################################################
### TEST 1 - Vérifier API
GET {{baseUrl}}/
Accept: {{contentType}}

############################################################
### TEST 2 - Créer un ADMIN
POST {{baseUrl}}/users/
Content-Type: {{contentType}}

{
  "nom": "Admin",
  "prenom": "System",
  "email": "admin@test.com",
  "password": "123456",
  "role": "ADMIN",
  "statut": "ACTIF"
}

############################################################
### TEST 3 - Créer un MANAGER
POST {{baseUrl}}/users/
Content-Type: {{contentType}}
Authorization: 
{
  "nom": "Manager",
  "prenom": "Fatou",
  "email": "manager@test.com",
  "password": "123456",
  "role": "MANAGER",
  "statut": "ACTIF"
}

############################################################
### TEST 4 - Créer un EMPLOYE
POST {{baseUrl}}/users/
Content-Type: {{contentType}}

{
  "nom": "Employe",
  "prenom": "Ali",
  "email": "employe@test.com",
  "password": "123456",
  "role": "EMPLOYE",
  "statut": "ACTIF"
}

############################################################
### TEST 5 - Lister les users
GET {{baseUrl}}/users/
Accept: {{contentType}}

############################################################
### TEST 6 - Login
POST {{baseUrl}}/auth/login/
Content-Type: {{contentType}}

{
  "email": "admin@test.com",
  "password": "123456"
}
