# Generated by Django 6.0.2 on 2026-02-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validée'), ('REJETE', 'Rejetée')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='absence',
            name='typeAbsence',
            field=models.CharField(choices=[('CONGE_ANNUEL', 'Congé annuel'), ('MALADIE', 'Maladie')], max_length=50),
        ),
    ]
