# Generated by Django 6.0.2 on 2026-02-18 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0002_alter_absence_statut_alter_absence_typeabsence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointage',
            old_name='user',
            new_name='employe',
        ),
        migrations.RemoveField(
            model_name='pointage',
            name='heure',
        ),
        migrations.RemoveField(
            model_name='pointage',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='pointage',
            name='type',
        ),
        migrations.AddField(
            model_name='pointage',
            name='est_retard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointage',
            name='heure_entree',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='heure_sortie',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='heures_sup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointage',
            name='minutes_retard',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QRCodeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_pointage', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
