# Generated by Django 6.0.2 on 2026-02-19 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0003_rename_user_pointage_employe_remove_pointage_heure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='typeAbsence',
        ),
        migrations.AddField(
            model_name='absence',
            name='type_absence',
            field=models.CharField(choices=[('CONGE_ANNUEL', 'Congé annuel'), ('CONGE_MALADIE', 'Congé maladie'), ('CONGE_EXCEPTIONNEL', 'Congé exceptionnel'), ('ABSENCE_NON_JUSTIFIEE', 'Absence non justifiée')], default='CONGE_ANNUEL', max_length=50),
        ),
        migrations.AlterField(
            model_name='absence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL),
        ),
    ]
