# Generated by Django 6.0.2 on 2026-02-19 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0004_remove_absence_typeabsence_absence_type_absence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='type_absence',
            new_name='typeAbsence',
        ),
        migrations.AlterField(
            model_name='absence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
