# Generated by Django 6.0.2 on 2026-02-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0005_rename_type_absence_absence_typeabsence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='typePointage',
            field=models.CharField(blank=True, null=True),
        ),
    ]
