# Generated by Django 6.0.2 on 2026-03-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0006_pointage_typepointage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='typePointage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
