# Generated by Django 6.0.2 on 2026-03-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0007_alter_pointage_typepointage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='absence',
            name='typeAbsence',
            field=models.CharField(choices=[('CONGE', 'Congé'), ('MALADIE', 'maladie'), ('MISSION', 'mission'), ('AUTRE', 'autre')], default='CONGE_ANNUEL', max_length=50),
        ),
    ]
